### ISSUE TITLE
Flatten Matrix

### ISSUE THREAD

**Issue by benjamin-lieser** [djugei/optimath#4]
It would be useful to have functionality to flatten a Matrix to a Vector (just reinterpreting it no copies)

**Comment by djugei** [comment]
Thanks for your interest, this was an exploratory project to see how rusts then new const-generics and mathemathics meshed, https://crates.io/crates/nalgebra is what you should probably use for serious stuff.

about the feature request: Matrices are currently built bottom-up so a matric is a vector<vector<T>>, therefore flattening them would require a transmute.  i tried building them top-down in https://github.com/djugei/optimath/blob/master/src/dimensional.rs though that was impossible due to lacking compiler functionality at that point.
